title: Coeur d'Alene Tech Group
subtitle: Uniting Lake City's technology community
email: dakotah@pena.name
description: >-
  The Coeur d'Alene Tech Group is a monthly meeting for tech industry people
  in or near Coeur d'Alene, Idaho.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cdatech.group"
github_url: https://github.com/dakotahp/cdatech.group
slack_url: http://slack.cdatech.group
meetup_url: https://www.meetup.com/Coeur-dAlene-Tech-Group/
feed_url: /feed.xml

# Build settings
markdown: kramdown
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
