# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coeur d'Alene Tech Group
subtitle: subtitle goes here
email: organizer@cdatech.group
description: >-
  The Coeur d'Alene Tech Group is a monthly meeting for tech industry people
  in or near Coeur d'Alene, Idaho. We exist for people involved in the tech scene
  including designers, software developers, system administrators, product people,
  entrepreneurs, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cdatech.group" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dakotahp
source: _source

# Build settings
markdown: kramdown
theme: jekyll-theme-prologue
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
