title: Coeur d'Alene Tech Group
subtitle: Uniting Lake City's technology community
email: organizer@cdatech.group
description: >-
  The Coeur d'Alene Tech Group is a monthly meeting for tech industry people
  in or near Coeur d'Alene, Idaho. We exist for people involved in the tech scene
  including designers, software developers, system administrators, product people,
  entrepreneurs, and more.
baseurl: "/cdatech.group" # the subpath of your site, e.g. /blog
url: "https://dakotahp.github.io/"
github_username: dakotahp

# Build settings
markdown: kramdown
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
