baseURL = "https://cdatech.group/"
languageCode = "en-us"
title = "Coeur d'Alene Tech Group"
sectionPagesMenu = "main"
publishDir = "docs"
copyright = "© Coeur d'Alene Tech Group"

[params]
  contactEmail = "dakotah@lakedistrict.space"
  slackUrl = "http://slack.cdatech.group/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
