source "https://rubygems.org"

gem 'jekyll', '~> 3.8.3'
gem 'jekyll-compose', group: [:jekyll_plugins]
gem 'jekyll-sitemap', group: [:jekyll_plugins]
gem 'jekyll-theme-prologue', '~> 0.3.2'
gem 'jekyll-feed', '~> 0.6', group: [:jekyll_plugins]

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
